apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
        - name: currency-exchange
          image: seifseddik120/currencyexchange:${BUILD_NUMBER}
          ports:
            - containerPort: 8080
